Разметка страниц
htmlacademy-htmlcss/2073605-sedona-34 pull request #2
Opened 2022-05-24 23:32 UTC by Yurii1980

2022-05-25 07:13 UTC, andreysgra requested changes

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +            <a class="navigation-link" href=" ">
В атрибуте `href` нужно указать ссылку на главную страницу.

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +            <a class="navigation-link navigation-link-current" href=" ">
В атрибуте `href` нужно указать ссылку на страницу каталога.

2022-05-25 07:13 UTC, andreysgra commented on index.html
> +            <a class="navigation-link" href=" ">
В атрибуте `href` нужно указать ссылку на главную страницу.

2022-05-25 07:13 UTC, andreysgra commented on index.html
> +            <a class="navigation-link" href=" ">
В атрибуте `href` нужно указать ссылку на страницу каталога.

2022-05-25 07:13 UTC, andreysgra commented on index.html
> +        <img src=" " alt="Логотип сайта городка Седона">
Если на странице каталога логотип является ссылкой, то почему здесь ссылки нет?

2022-05-25 07:13 UTC, andreysgra commented on index.html
> +        <img src=" " alt="Логотип сайта городка Седона">
В атрибуте `src` поставьте временную заглушку `#`. Иначе ошибка валидации HTML. Проверить можно [здесь](https://validator.w3.org/nu/#textarea).

2022-05-25 07:13 UTC, andreysgra commented on index.html
> +        <a type="button" href="#">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</a>
`type="button"` может быть только у тега `button`. У ссылки атрибута `type` нет.

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +            <button type="submit">Хочу сюда</button>
`type="submit"` используется для кнопки, которая находится в форме и отвечает за отправку данных. Но этот элемент интерфейса логичнее разметить не кнопкой, а ссылкой, так как предполагается переход на другую страницу.

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +
Лишняя пустая строка между тегами.

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +        <fieldset class="catalog-filter-group">
Вот это всё форма
![image](https://user-images.githubusercontent.com/17790771/170196586-99560607-4f25-49f2-b183-5775e7afbba2.png)
но тег формы у вас отсутствует. Стоит изучить [этот тренажёр](https://up.htmlacademy.ru/htmlcss/34/module/2/item/6), а также обратить внимание на [данный критерий]([HTML-04](https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-04)).

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +          <input type="range" id="dayscount" name="dayscount" min="1" max="9000" step="1">
Это не `type="range"`. Как видите, у него 2 ползунка, а у range один.
![image](https://user-images.githubusercontent.com/17790771/169681896-6f2f2448-1b3b-47b2-8c44-d6be0ae7070f.png)
Элементы, которые обвёл красным цветом можно разметить с помощью `button type="button"`, всё остальное - `div`.

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +          <input type="button" value="Сбросить">
1. У кнопок для отправки данных и для сброса значений полей есть соответствующие типы.
2. Вместо `input` используйте тег `button`.

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +            </div>
Лучше объединение элементов общим блоком сделать так:
![image](https://user-images.githubusercontent.com/17790771/169682178-f547b876-b2fd-4325-bc56-2815e49139db.png)

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +              <a class="button to-favorites" href="">В ИЗБРОННОЕ</a>
Текст не нужно писать заглавными буквами.

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +              <a class="button to-favorites" href="">В ИЗБРОННОЕ</a>
`"В избранное"`.
Чтобы не допускать ошибок и опечаток, текст лучше копировать непосредственно из макета:
![image](https://user-images.githubusercontent.com/17790771/170198125-19caae07-33ed-40df-a47d-c0ea4c76ba90.png)

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +        </form>
1. Форма здесь не нужна.
2. `select`, а не `input type="text"` (аналогично элементу "Сортировка").

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +
Лишние пустые строки.

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +        <form class="newsletter-form" action="#" method="post">
В `action` укажите `https://echo.htmlacademy.ru`.

2022-05-25 07:13 UTC, andreysgra commented on catalog.html
> +        <a class="htmlacademy" href="https://htmlacademy.ru/"></a>
Не по отдельности изображение и ссылка, а изображение внутри ссылки.

2022-05-25 07:13 UTC, andreysgra commented on index.html
> +          </li>
Этот блок
![image](https://user-images.githubusercontent.com/17790771/170199124-f8e42e26-a030-4034-bf6c-8776a68623c3.png)
нужно разметить отдельным списком, который будет вложенным в первый элемент списка `feature-list`:
```
<ul class="feature-list"
  <li class="feature-item-real-town">
    <h2 class="real-town">Настоящий городок</h2>
    <p class="irem-one">— №1 —</p>
    <p class="real-town-text">Седона — не аттракцион для туристов, там течет своя жизнь</p>
    <img src=" " alt="Улица городка">

    <ul>
      <li class="housing">
        <h3 class="housing">Жильё</h3>
        <p class="housing-text">Рекомендуем пожить в настоящем мотеле, всё как в кино!</p>
      </li>
      <!-- ... -->
    </ul>
  </li>
  <!-- ... -->
</ul>
```

2022-05-25 07:13 UTC, andreysgra commented on index.html
> +            <img src=" " alt="Домик">
Изображение декоративное и его не нужно вставлять в разметку. [Как отличить контентное изображение от декоративного](https://up.htmlacademy.ru/htmlcss/34/module/2/item/19)

2022-05-25 07:13 UTC, andreysgra commented on index.html
> +          </li>
Общее замечание по названию классов (касается не только этого блока, но и всего проекта в целом). Классы это CSS, а CSS нужно для оформления сайта. Давая название классу, нужно обращать внимание не только на контент, но и в немалой степени на оформление. Посмотрим на эти блоки:
![image](https://user-images.githubusercontent.com/17790771/170201148-281c9efb-02cd-4f19-a063-6c2fac1f61c3.png)
Внешний вид у них идентичен (если не считать небольших отличий в фоновом цвете), различается только содержимое. А так как CSS нужен для оформления, то названия классов у всех трёх блоков и классов элементов внутри них должны совпадать. Иначе вам для каждого блока придётся писать одни и те же стили.
Первый блок у вас `class="housing"`, второй `class="burger"`. Класс заголовка в первом блоке `class="housing"`, во втором `class="burger"`. Блоки одинаковые внешне, заголовки одинаковые, а классы разные.
И другая проблема, с которой столкнётесь в дальнейшем - у стилистически по разному оформленных элементов интерфейса должны быть разные названия классов. У вас, что общий блок, что его заголовок носят один и тот же класс `housing`.

2022-05-26 18:32 UTC, andreysgra requested changes
Уже значительно лучше, но ещё есть над чем поработать.

2022-05-26 18:32 UTC, andreysgra commented on index.html
> +            <button type="submit">Хочу сюда</button>
На странице каталога вы исправили кнопку на ссылку ([это](https://github.com/htmlacademy-htmlcss/2073605-sedona-34/pull/2#discussion_r881270117) замечание), а почему здесь, на главной странице не исправили? Шапка сайта одинакова для всех страниц.

> Если на странице (страницах) есть однотипные элементы в которых есть ошибка, то замечание я пишу только по первому элементу, где она встречается, но исправлять нужно везде.

2022-05-26 18:32 UTC, andreysgra commented on index.html
> +          </li>
Неправильно. [Здесь](https://github.com/htmlacademy-htmlcss/2073605-sedona-34/pull/2#discussion_r881287481) приводил пример кода. В первом `li` списка `feature-list` сначала идут элементы причины №1 и только потом вложенный список `reality-list`. Вы отвели под него отдельный `li`, который почему-то идёт первым.

2022-05-26 18:32 UTC, andreysgra commented on index.html
> +        <img src="" alt="Каньон">
В атрибуте `src` поставьте временную заглушку `#`.

2022-05-26 18:32 UTC, andreysgra commented on catalog.html
> +              <input type="text" max="0" placeholder="до">
У вас поля текстовые `type="text"`. У таких полей не может быть атрибутов `min` и `max`.

2022-05-26 18:32 UTC, andreysgra commented on catalog.html
> +              <button type="button" value="max"></button>
Кнопкам не нужны атрибуты `value`.

2022-05-26 18:32 UTC, andreysgra commented on catalog.html
> +            <button type="reset" value="Сбросить">
1. `button` тег парный, но вы забыли добавить закрывающий тег. То есть должно быть так: `<button type="submit">Применить</button>`.
2. Кнопкам не нужны атрибуты `value`.

2022-05-31 08:05 UTC, andreysgra requested changes
И давайте выполнять задания последовательно - пока не принято текущее задание, новое не начинать. Иначе так вся работа над проектом будет идти в рамках одного пулл реквеста.

2022-05-31 08:05 UTC, andreysgra commented on catalog.html
> +          <img class="page-header-logo" src="images/logo-sedona.svg" width="139" height="70" alt="Логотип сайта городка Седона">
[ALLY-01](https://up.htmlacademy.ru/htmlcss/34/criteries#ALLY-01) - подпись в конце описания **должна** иметь точку. Исправьте во всех `alt`.

2022-05-31 20:05 UTC, Yurii1980 commented
> И давайте выполнять задания последовательно - пока не принято текущее задание, новое не начинать. Иначе так вся работа над проектом будет идти в рамках одного пулл реквеста.

Понял

2022-06-01 05:08 UTC, merged